# version: '3.4'

services:
  coverage-pluxnet-nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:5173:5173"
    networks:
      - bridge


networks:
  bridge:
