# version: '3.4'

services:
  coverage-nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      #- "127.0.0.1:3022:80" # access via http://localhost:3000
      - "3022:80"
    restart: unless-stopped
    networks:
      - default
      - public-proxy

volumes:
  coverage-nextjs:

networks:
  default:
    name: coverage_default
  public-proxy:
    external: true